name: 'Test Coverage'
description: 'Generates and uploads a test coverage report.'
inputs:
  codecov-token:
    description: 'The Codecov token'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      with:
        extra-packages: any::covr, any::xml2
        needs: coverage

    - name: Test coverage
      shell: Rscript {0}
      run: |
        cov <- covr::package_coverage(
          quiet = FALSE,
          clean = FALSE,
          install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
        )
        covr::to_cobertura(cov)

    - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
      with:
        # Fail if error if not on PR, or if on PR and token is given
        fail_ci_if_error: ${{ github.event_name != 'pull_request' || inputs.codecov-token }}
        files: ./cobertura.xml
        plugins: noop
        disable_search: true
        token: ${{ inputs.codecov-token }}

    - name: Show testthat output
      if: always()
      shell: bash
      run: |
        ## --------------------------------------------------------------------
        find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: coverage-test-failures
        path: ${{ runner.temp }}/package
