name: 'Style and Document'
description: 'Automatically styles and documents the R code in a package.'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      with:
        extra-packages: |
          any::styler
          any::roxygen2
          any::desc
        needs: |
          website
          coverage

    - name: Enable styler cache
      shell: Rscript {0}
      run: styler::cache_activate()

    - name: Determine cache location
      id: styler-location
      shell: Rscript {0}
      run: |
        cat(
          "location=",
          styler::cache_info(format = "tabular")$location,
          "\n",
          file = Sys.getenv("GITHUB_OUTPUT"),
          append = TRUE,
          sep = ""
        )

    - name: Cache styler
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ${{ steps.styler-location.outputs.location }}
        key: ${{ runner.os }}-styler-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-styler-
          ${{ runner.os }}-

    - name: Style
      shell: Rscript {0}
      run: styler::style_pkg()

    - name: Commit and push changes
      id: commit_step_style
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "Style code (GHA)"
      continue-on-error: true

    - name: Create Pull Request
      if: ${{ steps.commit_step_style.outputs.changes_detected == 'true' && steps.commit_step_style.outcome == 'failure' }}
      uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
      with:
        commit-message: "Style code (GHA)"
        branch: auto-style-code
        delete-branch: true
        title: "Style code (GHA)"
        labels: maintenance
        base: ${{ github.event.pull_request.base.ref }}
        body: |
          This Pull Request was automatically created to apply styling changes to your code.
          Please review and merge this PR.
        assignees: ${{ github.actor }}
        reviewers: ${{ github.actor }}

    - name: Normalise DESCRIPTION
      shell: Rscript {0}
      run: desc::desc_normalize()

    - name: Document
      shell: Rscript {0}
      run: roxygen2::roxygenise()

    - name: Commit and push changes
      id: commit_step_document
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "Document package (GHA)"
      continue-on-error: true

    - name: Create Pull Request
      if: ${{ steps.commit_step_document.outputs.changes_detected == 'true' && steps.commit_step_document.outcome == 'failure' }}
      uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
      with:
        commit-message: "Document package (GHA)"
        # Use a different branch name than the style PR
        branch: auto-document-code
        delete-branch: true
        title: "Document package (GHA)"
        labels: maintenance
        base: ${{ github.event.pull_request.base.ref }}
        body: |
          This Pull Request was automatically created to apply documentation changes to your code.
          Please review and merge this PR.
        assignees: ${{ github.actor }}
        reviewers: ${{ github.actor }}
