name: 'Extended R CMD Check'
description: 'Runs an extended set of R CMD checks for a package on a specific OS and R version.'
inputs:
  r-version:
    description: 'The R version to use'
    required: true
  http-user-agent:
    description: 'The HTTP user agent to use for setup-r'
    required: false
runs:
  using: "composite"
  steps:
    - uses: r-lib/actions/setup-pandoc@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
    - uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      with:
        r-version: ${{ inputs.r-version }}
        http-user-agent: ${{ inputs.http-user-agent }}
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      with:
        extra-packages: any::rcmdcheck
        needs: check
    - uses: r-lib/actions/check-r-package@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      with:
        upload-snapshots: true
        build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
